@BASE_URL = https://react-album-1a909-default-rtdb.firebaseio.com/

POST {{BASE_URL}}albums.json 
Content-Type: application/json

 {
    "id": 1,
    "name": "Album",
    "photos": [
      {
        "id": 1,
        "name": "Immerse into the Falls",
        "date": "5/12/2023",
        "description": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolores maiores officiis quae distinctio ipsa vitae nobis consectetur dolor enim in!",
        "image": "https://tcproduction.blob.core.windows.net/media/%7B240f8b72-1159-4fd3-a150-0a837f50ba4a%7D.2573758641_297d6d19fa_o.jpg"
      },
      {
        "id": 2,
        "name": "Helicopter Over the Falls",
        "date": "8/12/2023",
        "description": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolores maiores officiis quae distinctio ipsa vitae nobis consectetur dolor enim in!",
        "image": "https://d2ru2mvuh5wx24.cloudfront.net/avtivity_bootstrap/1241/flight_of_angels_3__1920x864.jpg"
      },
      {
        "id": 3,
        "name": "The Falls at Night",
        "date": "2/12/2023",
        "description": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolores maiores officiis quae distinctio ipsa vitae nobis consectetur dolor enim in!",
        "image": "https://www.niagarafallsstatepark.com/~/media/parks/niagara-falls/attractions-and-tours/illumination/niagarafalls-illumination-header-desktop.jpg?h=500&w=1500&la=en&hash=123E6D5F1744FBCC74EC36570E77872608D24891g"
      },
      {
        "id": 4,
        "name": "Immerse into the Falls",
        "date": "5/12/2023",
        "description": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolores maiores officiis quae distinctio ipsa vitae nobis consectetur dolor enim in!",
        "image": "https://tcproduction.blob.core.windows.net/media/%7B240f8b72-1159-4fd3-a150-0a837f50ba4a%7D.2573758641_297d6d19fa_o.jpg"
      },
      {
        "id": 5,
        "name": "All Around the World",
        "date": "5/12/2023",
        "description": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolores maiores officiis quae distinctio ipsa vitae nobis consectetur dolor enim in!",
        "image": "https://assets.simpleviewcms.com/simpleview/image/upload/c_limit,h_1200,q_75,w_1200/v1/clients/lasvegas/strip_b86ddbea-3add-4995-b449-ac85d700b027.jpg"
      },
      {
        "id": 6,
        "name": "Show me the Magic",
        "date": "8/12/2023",
        "description": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolores maiores officiis quae distinctio ipsa vitae nobis consectetur dolor enim in!",
        "image": "https://footwearnews.com/wp-content/uploads/2020/10/magic-trade-show-las-vegas.jpg"
      },
      {
        "id": 7,
        "name": "The Falls at Night",
        "date": "2/12/2023",
        "description": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolores maiores officiis quae distinctio ipsa vitae nobis consectetur dolor enim in!",
        "image": "https://assets.simpleviewcms.com/simpleview/image/upload/c_limit,h_1200,q_75,w_1200/v1/clients/lasvegas/strip_b86ddbea-3add-4995-b449-ac85d700b027.jpg"
      }
    ]
  }



###
GET {{BASE_URL}}albums.json